### ISSUE TITLE
Choose FlexSlider style via CMS

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-flexslider#1]
Allow users to choose a style for FlexSlider. Select and implement the most useful examples from Flexslider Live Demo:

http://flexslider.woothemes.com

The 'slider w/ thumbnail slider' would be useful for a photo gallery:

http://flexslider.woothemes.com/thumbnail-slider.html

**Comment by muskie9** [comment]
We can definitely integrate this in. @korthjp17 we'll need to update the `FlexSlider.ss` include to check for the option once it's added in and the init for it will need to go into the `onAfterInit()` in FlexSliderExtension.php.

I may look into trying to utilize `$this->extend()` in `Page_Controller` to see if we can avoid the `onAfterInit()` as it's made some issues in the past.

We'll need to do quite a bit of usability testing with this as the more options we add the more points of failure there could be with the UI.

**Comment by korthjp17** [comment]
This is the chunk we we need that adds the init 
https://gitlab.com/dynamic-inc-sites/kohler-global-projects/blob/master/mysite/code/pages/Reference.php#L102

this is the chunk in the include:
https://gitlab.com/dynamic-inc-sites/kohler-global-projects/blob/master/themes/kcaw/templates/Includes/FlexSliderThumb.ss#L16
