### ISSUE TITLE
QUESTION is flex slider_init.js still required?

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-flexslider#13]
Since we have the `onAfterInit()` function do should we drop the `slider_init.js` file?

**Comment by muskie9** [comment]
@jsirish @korthjp17 do you guys know if this file is being used at all?

**Comment by korthjp17** [comment]
I don't believe it is, I think it gets initialized from the onAfterInit()

**Comment by jsirish** [comment]
Not sure, will defer to Korth


I don't believe it is, I think it gets initialized from the onAfterInit()

**Comment by jsirish** [comment]
closed via #49
