### ISSUE TITLE
No 'Slider' Tab in CMS

### ISSUE THREAD

**Issue by mhenden** [dynamic/silverstripe-flexslider#136]
I've used Flexslider for a number of years but suddenly I'm having problems getting a 'Slider' tab to load in the SilverStripe 4.1 CMS. I'm wondering what I'm missing? Can anybody help?

**Comment by korthjp17** [comment]
@mhenden Which version are you currently using? Also, how are you applying the slides?

**Comment by mhenden** [comment]
@korthjp17 , I'm using SilverStripe 4.2. Can't apply slides as I don't have the requisite tab in the left sidebar of CMS interface.

**Comment by muskie9** [comment]
@mhenden can you run `composer info` and post the results, just want to make sure we match up all versions when testing.

**Comment by mhenden** [comment]
Is this what you want? 
`composer/installers      v1.0.18 A multi-framework Composer library installer
guzzle/common            v3.9.2  Common libraries used by Guzzle
guzzle/http              v3.9.2  HTTP libraries used by Guzzle
guzzle/parser            v3.9.2  Interchangeable parsers used by Guzzle
guzzle/stream            v3.9.2  Guzzle stream wrapper component
omnipay/omnipay          v1.1.0  A framework agnostic, multi-gateway paymen...
silverstripe/framework   3.1.6   The SilverStripe framework
symfony/event-dispatcher v2.5.5  Symfony EventDispatcher Component
symfony/http-foundation  v2.5.5  Symfony HttpFoundation Component`

**Comment by muskie9** [comment]
Just checking, did you run that from the webroot where your site is? Looks like it's referencing SS 3.1.6 and not seeing our flexslider package.

**Comment by mhenden** [comment]
Sorry -- 'my bad'...
`Mikes-Mac-Pro:Silverstripe-4.1 mikehenden$ composer info
composer/ca-bundle                        1.1.0             
composer/installers                       v1.5.0            
doctrine/instantiator                     1.0.5             
dynamic/flexslider                        dev-master ff38b5b
embed/embed                               v3.3.1            
guzzlehttp/psr7                           1.4.2             
intervention/image                        2.4.1             
league/flysystem                          1.0.43            
m1/env                                    2.1.0             
marcj/topsort                             1.1.0             
monolog/monolog                           1.23.0            
myclabs/deep-copy                         1.7.0             
nikic/php-parser                          v3.1.5            
paragonie/random_compat                   v2.0.11           
phpdocumentor/reflection-common           1.0.1             
phpdocumentor/reflection-docblock         4.3.0             
phpdocumentor/type-resolver               0.4.0             
phpspec/prophecy                          1.7.5             
phpunit/php-code-coverage                 4.0.8             
phpunit/php-file-iterator                 1.4.5             
phpunit/php-text-template                 1.2.1             
phpunit/php-timer                         1.0.9             
phpunit/php-token-stream                  2.0.2             
phpunit/phpunit                           5.7.27            
phpunit/phpunit-mock-objects              3.4.4             
psr/cache                                 1.0.1             
psr/container                             1.0.0             
psr/http-message                          1.0.1             
psr/log                                   1.0.2             
psr/simple-cache                          1.0.1             
sebastian/code-unit-reverse-lookup        1.0.1             
sebastian/comparator                      1.2.4             
sebastian/diff                            1.4.3             
sebastian/environment                     2.0.0             
sebastian/exporter                        2.0.0             
sebastian/global-state                    1.1.1             
sebastian/object-enumerator               2.0.1             
sebastian/recursion-context               2.0.0             
sebastian/resource-operations             1.0.0             
sebastian/version                         2.0.1             
silverstripe-themes/simple                dev-master c2fdd14
silverstripe/admin                        1.1.0             
silverstripe/asset-admin                  1.1.0             
silverstripe/assets                       1.1.0             
silverstripe/campaign-admin               1.1.0             
silverstripe/cms                          4.1.0             
silverstripe/config                       1.0.4             
silverstripe/errorpage                    1.1.0             
silverstripe/framework                    4.1.0             
silverstripe/graphql                      1.1.0             
silverstripe/recipe-cms                   1.1.0             
silverstripe/recipe-core                  1.1.0             
silverstripe/recipe-plugin                1.1.0             
silverstripe/reports                      4.1.0             
silverstripe/siteconfig                   4.1.0             
silverstripe/vendor-plugin                1.3.1             
silverstripe/versioned                    1.1.0             
swiftmailer/swiftmailer                   v5.4.9            
symbiote/silverstripe-gridfieldextensions 3.1.1             
symfony/cache                             v3.4.6            
symfony/config                            v3.4.6            
symfony/filesystem                        v3.4.6            
symfony/finder                            v3.4.6            
symfony/polyfill-apcu                     v1.7.0            
symfony/polyfill-mbstring                 v1.7.0            
symfony/translation                       v2.8.36           
symfony/yaml                              v3.4.6            
webmozart/assert                          1.3.0             
webonyx/graphql-php                       v0.8.0 `

**Comment by muskie9** [comment]
No worries @mhenden, I've tested the module on a fresh ss installation (4.1.0) and am seeing the slides tab. Do you have any `DataExtension` classes updating cms fields other than the Flexslider that may be causing an issue? For additional support you can find us online on the SS slack community channel: silverstripe-users.slack.com. Might be quicker troubleshooting there ;)

**Comment by muskie9** [comment]
@mhenden just wanted to check in and see if you were able to make any additional progress on this.

**Comment by mhenden** [comment]
Hi @muskie9 , got a bit snowed last week but back onto this now. Like you I did a straight install of SS4.1 'out of the box' -- I haven't added anything other than Flexslider. I have set up config file mysite.yml (contents below) but no Flexslider tab... 

---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite

Page:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider

**Comment by muskie9** [comment]
Hi @mhenden, sorry we never got back to this ticket. If this is still an issue feel free to comment. Closing for now in favor of newer releases.
