### ISSUE TITLE
Slide links not being used in templates

### ISSUE THREAD

**Issue by Juanitou** [dynamic/silverstripe-flexslider#159]
I'm using the latest version,  4.0.0-beta3. If I understand it well, since the transition to the Linkable module, the CMS saves slide links in a `SlideLink` field instead of the old `PageLink`. A migration task for these fields has been written and seems to work, but the templates are still referencing `$PageLink`, so slides are not getting new or updated links.

I could try providing a patch for the templates, but the [Linkable](http://github.com/sheadawson/silverstripe-linkable) module seems unmaintained and so the changes should concern a larger portion of the code than I'm able to tackle.

**Comment by muskie9** [comment]
Thanks for reporting @Juanitou. As mentioned in your ticket, Linkable has been marked as unmaintained, so we're reviewing other options and should have a decision on a linking module direction. We've been testing out [gorriecoe/silverstripe-linkfield](https://github.com/gorriecoe/silverstripe-linkfield) and it seems to be similar to what we were used to with linkable. The silverstripe-linkfield module has a larger discussion going [here as well](https://forum.silverstripe.org/t/new-links-module/1642).

We'll update the ticket as soon as we have our next steps ready.

**Comment by muskie9** [comment]
resolved via #180
