### ISSUE TITLE
Can not find the FlexSlider.ss template

### ISSUE THREAD

**Issue by MichelleZZZZ** [dynamic/silverstripe-flexslider#184]
## Affected Version
framework  version: 4.31.1
dynamic/flexslider "version": "4.0.0"

## Description
The FlexSlider template is not pulling from the Includes folder.
Error got on frontend:
None of the following templates could be found: Array ( [0] => Array ( [type] => Includes [0] => FlexSlider ) [1] => FlexSlider

## Steps to Reproduce
One of my another site is using 4.0.0-beta3 which do not have this issue.
In version 4.0.0:
The folder structure under the "templates" folder is different from 4.0.0-beta3.
If take the Includes folder directly under the templates folder, it will working.

Please have a look. Thanks

**Comment by muskie9** [comment]
This is likely the same as #183

**Comment by korthjp17** [comment]
I think #183 would solve this issue, but moving the Includes folder up to live right under Templates would also work. Will do some testing and get it fixed.
