### ISSUE TITLE
Recursive Lookup for Flexslider

### ISSUE THREAD

**Issue by mhenden** [dynamic/silverstripe-flexslider#201]
**Not so much an issue as much as a request -- or maybe this feature is already there?**

I'm updating an Silverstripe 3 site that uses Flexslider for a branding strip that runs on all pages. In SS3 slides were set up via a 'Slider' tab in the left hand sidebar of the CMS and all I have to do was have `Flexslider(1,1200,380)` in my template for the same slider to load on every page. 

Now, of course, there is a 'slider' field in the CMS for a nominated Page type. Editors set up sliders for individual pages using this field. So is there a way to set this up 'globally' so it appears on all pages, or a group of pages? Can't see this in the CMS and I can't see how to format my templates so that this happens?

_Just asking..._

**Comment by muskie9** [comment]
Hi @mhenden,

Were you previously using this same package for your flexslider implementation? I don't recall the behavior you've described with the Model Admin and template.

**Comment by mhenden** [comment]
Hi Nic, this was the really (as in really really) old version (pre Dynamic) that was set up in this manner. It's since Dynamic took the project over that the 'Slider' field appeared on individual pages instead of being a 'global' setting in the CMS margin. I was just wondering if there was a simple way to offer this option (ie repeat the same slider on a range of pages instead of setting sliders up individually)?

**Comment by muskie9** [comment]
@mhenden I think it's possible by setting up a DataObject and Model Admin to manage that class, then add the FlexSlider DataExtension to the new DataObject. You could then have a dropdown/has_one field to select which slider you'd like to use on pages. That should allow you to build multiple (global-esque) sliders for use across the site.

This feature wouldn't be something we would add to the module itself unfortunately as the implementation/usage by developers vary by project/developer, such as your use case. The module is flexible enough to allow for various implementations, but it's core functionality is what we can consistently maintain.

**Comment by mhenden** [comment]
Thanks for the pointers Nic. I'll check this out. My PHP skills are not that flash but I'll have a play and see what I can do!

**Comment by muskie9** [comment]
Sounds good, I'll close this ticket. You can usually find some of us in the [Silverstripe Community Slack](https://www.silverstripe.org/community/slack-signup/) if you haven't used that yet. The community's really great overall!

**Comment by mhenden** [comment]
Hey Nic, one more question -- where is the image size for Flexslider determined? I know it's something like '1200,600' ??

**Comment by muskie9** [comment]
I think in our use cases we generally have the image dynamically resized via the css grid. We generally inform clients of the dimensions for the largest breakpoint so it doesn't scale up. You could copy the templates/includes to your theme and set the dimensions using Silverstripe's image manipulation methods in the template(s).
