### ISSUE TITLE
Write Readme

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-flexslider#3]

**Comment by muskie9** [comment]
@jsirish can you take a look at my [README branch](https://github.com/muskie9/SilverStripe-FlexSlider/tree/README) and let me know if I missed anything. I can probably do an additional how-to section for setting up the flex slider init stuff. I mentioned applying it to DataObject or a page type. If we need to go in depth for each (as DataObject requires some extra love for the init) we may want to setup a github page for the docs.

**Comment by jsirish** [comment]
I think it looks great! 

I'd probably add something about the FlexSlider.ss include to use in their templates. Otherwise it seems thorough.

We should probably do a GitHub page for this and all the other modules. An example for each would be helpful, thinking back to being a noob.

**Comment by jsirish** [comment]
closed via #41
